### ISSUE TITLE
Input size is 224x224 instead of ~80x80 for mini-imagenet?

### ISSUE THREAD

**Issue by peiswang** [hushell/pmf_cvpr22#10]
Hi,
Thanks for your greate work! It seems that the defualt input image size for mini-imagenet in the released code is 224x224. Are the results of the paper all use 224x224 as input for mini-imagenet? Thanks!

**Comment by hushell** [comment]
Hello, 

This is because ViT backbones work better with 224x224. With this change, TBH it becomes tricky to compare applies to bananas so it would be better to redo ResNet mini-Imagenet experiments with 224x224. We recommend to use our PMF setting as a new setting (i.e., introducing self-supervised pre-training) to few-shot learning and only compare methods in this new setting.

**Comment by peiswang** [comment]
Got it. Thank you very much for your reply.
