### ISSUE TITLE
cross-domain sample CDFSL, the following error occurred.

### ISSUE THREAD

**Issue by githubdds** [hushell/pmf_cvpr22#22]
Thank you very much for the contributed code repository. When testing on the cross-domain sample CDFSL, the following error occurred.![image](https://github.com/hushell/pmf_cvpr22/assets/133148792/de5c47a9-160d-46e3-a8fb-749353f2249f) When testing 600 samples, an error will occur, "metric_logger has no attribute loss". Thank you very much. 🙏

**Comment by githubdds** [comment]
<img width="753" alt="image" src="https://github.com/hushell/pmf_cvpr22/assets/133148792/a237b320-149f-4a02-bb46-17b1d2b9588c">

**Comment by hushell** [comment]
Thanks for your interests! If still relevant: 
It looks like [engine.py#L120](https://github.com/hushell/pmf_cvpr22/blob/main/engine.py#L120) was not executed, otherwise `metric_logger` should have a `loss` attribute. You may want to set up a breakpoint at that line to see what happened. It's probably due to the CDFSL dataset is incomplete or something like that.
