### ISSUE TITLE
label

### ISSUE THREAD

**Issue by RenYangSCU** [hushell/pmf_cvpr22#4]
I cann't get the [imagelabels.mat](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/imagelabels.mat) from the website.Where can I get this label?Can you share the label?Thank you!

**Comment by hushell** [comment]
Hi @EllieSeven Sorry for late reply! It seems you have solved the problem already. I found where you need this mat file: https://github.com/google-research/meta-dataset/blob/main/doc/dataset_conversion.md#vgg_flower
Just follow this instruction.

**Comment by RenYangSCU** [comment]
Thank  you for your reply! I have solved this problem already. But I got another problem. When converting tfrecords to h5 using [scripts/convert_tfrecord_to_h5.py](file:///D:/codes/pmf_cvpr22/scripts/convert_tfrecord_to_h5.py). , I meet a bug
`OSError: D:\codes\pmf_cvpr22\datasets_convert\ilsvrc_2012\0.index not found.`. I only got tfrecords files and dataset_spec_json. How can I solve this problem? Using [datasets\meta_dataset\tfrecord\tools\tfrecord2idx.py](file:///D:/codes/pmf_cvpr22/datasets/meta_dataset/tfrecord/tools/tfrecord2idx.py) can produce index files?

**Comment by hushell** [comment]
Right... sorry I should have included this step, since the tfrecord conversion is done by [https://github.com/mboudiaf/pytorch-meta-dataset](url): 
 [https://github.com/mboudiaf/pytorch-meta-dataset/blob/61e8555dda0ef75e80cf3d03cb0d7a6822b0e082/Makefile#L233](https://protect2.fireeye.com/v1/url?k=ff74c528-9e0f6fbf-ff754e67-74fe4860001d-b55aba88169355b0&q=1&e=dda74f82-d567-4829-af92-805738fca81c&u=https%3A%2F%2Fgithub.com%2Fmboudiaf%2Fpytorch-meta-dataset%2Fblob%2F61e8555dda0ef75e80cf3d03cb0d7a6822b0e082%2FMakefile%23L233) 

We add hdf5 cache to make data loading faster.

**Comment by hushell** [comment]
The index files are used by [https://github.com/hushell/pmf_cvpr22/blob/6bfb8670c1f38e33a25e84065331c18ad78e1201/datasets/meta_dataset/reader.py#L57](https://protect2.fireeye.com/v1/url?k=e22f80bb-83526a38-e22e0bf4-74fe48600158-9608fb13a1c26225&q=1&e=6276ce3a-a75a-464e-a4fa-ff7573d32498&u=https%3A%2F%2Fgithub.com%2Fhushell%2Fpmf_cvpr22%2Fblob%2F6bfb8670c1f38e33a25e84065331c18ad78e1201%2Fdatasets%2Fmeta_dataset%2Freader.py%23L57)

**Comment by RenYangSCU** [comment]
OK, I got it. Thank you very much!!!
